print("##############################")
print("#                            #")
print("#   Fathiah Nuraisyah Radam  #")
print("#       2210817120013        #")
print("#                            #")
print("##############################")